const MAIL_SERVICE_ID = process.env.NEXT_PUBLIC_MAIL_SERVICE_ID;
const MAIL_SERVICE_PUBLIC_KEY = process.env.NEXT_PUBLIC_MAIL_SERVICE_PUBLIC_KEY;
const MAIL_SERVICE_PRIVATE_KEY = process.env.NEXT_PUBLIC_MAIL_SERVICE_PRIVATE_KEY;
const TEMPLATEID = process.env.NEXT_PUBLIC_MAIL_SERVICE_TEMPLATE_ID;

export { MAIL_SERVICE_ID, MAIL_SERVICE_PUBLIC_KEY, MAIL_SERVICE_PRIVATE_KEY, TEMPLATEID };
