import type { Metadata } from 'next';
import { Geist } from 'next/font/google';
import CanvasCursor from '@/components/global/CanvaCursor';
import { ThemeProvider } from '@/components/theme-provider';
import { cn } from '@/lib/utils';
import '@/css/globals.css';
import Navbar from '@/components/global/public-navbar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Thienmdp Portolio',
  description: 'Generated by Thienmdp Portolio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={cn('min-h-screen overflow-x-hidden font-sans antialiased', geistSans.variable)}
      >
        <ThemeProvider attribute='class' defaultTheme='dark' enableSystem disableTransitionOnChange>
          <Navbar />
          {/* <PublicNavbar /> */}
          {children}
          <CanvasCursor />
        </ThemeProvider>
      </body>
    </html>
  );
}
